# Generated by Django 3.2 on 2021-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
                ('condition', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
