# Generated by Django 3.2.4 on 2021-06-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='product.memberships'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
