# Generated by Django 3.2.4 on 2021-07-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bid_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_product', to='product.product'),
        ),
    ]
