# Generated by Django 3.2.4 on 2021-07-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_bidding_bid_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_product', to='product.product'),
            preserve_default=False,
        ),
    ]
