# Generated by Django 3.2.4 on 2021-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210705_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Rejected', max_length=100),
        ),
    ]
