# Generated by Django 3.2.4 on 2021-07-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_bidding_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='status',
            new_name='bid_status',
        ),
    ]
