# Generated by Django 3.2.4 on 2021-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_rename_status_bidding_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Reject', max_length=100),
        ),
    ]
