# Generated by Django 3.2.4 on 2021-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_bidding_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
